#!/bin/sh

cp -v .xinitrc.sample /usr/local/bin/startdwm
chmod -v +x /usr/local/bin/startdwm

cp -v statusbar /usr/local/bin/

cp -v wallpaper.png "$HOME/.config/"

cp -v dwm.desktop /usr/share/xsessions/
