#!/bin/bash

delim='|'

status(){
    # volume
    mute=$(pulsemixer --get-mute)
    if [[ $mute == 1 ]]; then
        echo "Mute vol."
    else
        pulsemixer --get-volume | awk '{print $1 "% vol."}'
    fi
    echo "$delim"

    # internet connection status
    sed "s/down/Internt down/;s/up/Internt up/" /sys/class/net/w*/operstate
    echo "$delim"

    date "+%d %b %Y (%a) %H:%M"
    }

while :; do
    # tr is used to remove newlines because it does not render good
    xsetroot -name "$(status | tr '\n\' ' ')"

    sleep 1m
done
