#!/bin/bash

delim='|'

status(){
    # volume
    #    
    mute=$(pulsemixer --get-mute)
    if [[ $mute == 1 ]]; then
        echo ""
    else
        volume=$(pulsemixer --get-volume | awk '{print int($1 * 100/150)}')

        case $volume in
            100|[6-9][0-9]) v_icon=" " ;;
            [1-5][0-9]) v_icon="" ;;
            *)  v_icon="" ;;
        esac

        echo "$v_icon$volume%"
    fi
    echo "$delim"

    # Bluetooth
    #    

    # Ethernet
    # e* indicates ethernet connection
    # if you have wnat to indicate if a wifi is connected just change it to w*
    #     ,
    ethernet=$(cat /sys/class/net/e*/operstate)
    if [ ethernet = 'up']; then
        echo ""
    else
        # Wifi quality percentage and up/down if ethernet is connected
        #       
        grep "^\s*w" /proc/net/wireless | awk '{ print "", int($3 * 100 / 70) "%" }'
    fi
    echo "$delim"

    # Battery
    #        
    for capacity in /sys/class/power_supply/BAT?/capacity;
    do
    case "$(cat $capacity)" in
        100) echo "" ;;
        9[0-9]) echo "" ;;
        8[0-9]|7[0-9]) echo "" ;;
        6[0-9]|5[0-9]) echo "" ;;
        4[0-9]|3[0-9]) echo "" ;;
        2[0-9]) echo "" ;;
        1[0-9]) echo "" ;;
        [0-9]) echo "" ;;
    esac
    done

    echo "$delimiter"

    date "+%d %b %Y (%a) %H:%M"
    }

while :; do
    # tr is used to remove newlines because it does not render good
    xsetroot -name "$(status | tr '\n\' ' ')"

    sleep 1m
done
