#!/bin/bash
source "$HOME/.local/bin/utils"

DELIM='|'
status(){
    # weather
    timeout 5s weather -s || echo 'weather script is taking too long'
    echo "$DELIM"

    # volume
    vc -i
    echo "$DELIM"

    # Bluetooth
    #    

    # Ethernet
    # "$HOME/.local/bin/ethernet"
    wifi
    echo "$DELIM"

    # Battery
    #        
    # Print all batteries, their percentage remaining and an icon corresponding to charge status
    for battery in /sys/class/power_supply/BAT?;
    do
        # if battery folder does not exist exit from loop
        [ -d "$battery" ] || break

        capacity=$(cat "$battery"/capacity) || break
        status=$(cat "$battery"/status)

        if [ "$status" = "Charging" ] || [ "$status" = "Full" ]; then
            b_icon=" "
        else
            # If it is discharging and 25% or less, we will add a ! as a warning
            [ "$status" = "Discharging" ] && [ "$capacity" -le 25 ] && warn="(!)" && $(notify-send -u critical "Battery low")

            case $capacity in
                100) b_icon="" ;;
                9[0-9]) b_icon="" ;;
                8[0-9]|7[0-9]) b_icon="" ;;
                6[0-9]|5[0-9]) b_icon="" ;;
                4[0-9]|3[0-9]) b_icon="" ;;
                2[0-9]) b_icon="" ;;
                1[0-9]) b_icon="" ;;
                [0-9]) b_icon="" ;;
            esac
        fi

        echo "$b_icon$capacity% $warn"
        echo "$DELIM"
    done

    # updatable packages
    #   

    if is_installed apt; then
        # for debia systems
        n_packages=$(apt list --upgradable 2>/dev/null | grep upgradable | wc -l)
    elif is_installed checkupdates; then
        # for arch systems
        n_packages=$(checkupdates 2>/dev/null | wc -l)
    else
        n_packages="NaN"
    fi


    echo " $n_packages"

    echo "$DELIM"

    date "+%d %b %Y (%a) %H:%M"
    }

while :; do
    # tr is used to remove newlines because it does not render good
    xsetroot -name "$(status | tr '\n' ' ')"
    sleep 1m
done
